// tunnel/internal/server/admin/web/src/pages/app/connections.svelte
<script lang="ts">
  import DataTable from "$lib/components/data-table.svelte";
  // @ts-expect-error
  import { createTable, createRender } from "svelte-headless-table";
  import { humanizeTimeMs } from "$lib/humanize";
  import { Checkbox } from "$lib/components/ui/checkbox";
  import Label from "$lib/components/ui/label/label.svelte";
  import { connections, connectionsLoading } from "$lib/store";
  import type { Connection } from "$lib/types";
  import { getContext } from "svelte";
  import ConnectionStatus from "$lib/components/ConnectionStatus.svelte";
  import ConnectionType from "$lib/components/ConnectionType.svelte";
  import DateField from "$lib/components/DateField.svelte";
  import Pagination from "$lib/components/Pagination.svelte";
  import { writable } from "svelte/store";
  import { updateQueryParam } from "$lib/utils";
  import * as Card from "$lib/components/ui/card";

  let checked = false;
  const urlParams = new URLSearchParams(window.location.search);
  let connectionType = urlParams.get("type") || "recent";

  let pageNo = writable(1);
  let pageNoStr = urlParams.get("page") || "1";
  pageNo.set(parseInt(pageNoStr, 10) || 1);

  $: if (checked) {
    if (connectionType === "recent") {
      connectionType = "active";
      pageNo.set(1);
    }
  } else {
    if (connectionType === "active") {
      connectionType = "recent";
      $pageNo = 1;
    }
  }

  $: updateQueryParam(urlParams, "type", connectionType);
  $: updateQueryParam(urlParams, "page", $pageNo.toString());
  $: getConnections(connectionType, $pageNo.toString());

  let team = getContext("team") as string;

  let totalItems = 0;

  const getConnections = async (
    type: string = "recent",
    pageNo: string = "1"
  ) => {
    connectionsLoading.set(true);
    try {
      const response = await fetch(
        `/api/v1/connections/?type=${type}&page=${pageNo}`,
        {
          headers: {
            "x-team-slug": team,
          },
        }
      );
      const responseData = await response.json();
      connections.set(responseData["data"] || []);
      totalItems = responseData.count;
    } catch (err) {
      console.error(err);
    } finally {
      connectionsLoading.set(false);
    }
  };

  const table = createTable(connections);

  const columns = table.createColumns([
    table.column({
      header: "Type",
      accessor: (item: Connection) => item,
      cell: ({ value: { type } }: { value: { type: string } }) =>
        createRender(ConnectionType, { type }),
    }),
    table.column({
      header: "Port",
      accessor: (item: Connection) => {
        const { port } = item;
        return port ? port : "-";
      },
    }),
    table.column({
      header: "Subdomain",
      accessor: (item: Connection) => {
        const { subdomain } = item;
        return subdomain ? subdomain : "-";
      },
    }),
    table.column({
      accessor: (item: Connection) => item,
      header: "Status",
      cell: ({ value: { status } }: { value: { status: string } }) =>
        createRender(ConnectionStatus, { status }),
    }),
    table.column({
      accessor: (item: Connection) => item,
      header: "Created at",
      cell: (item: any) =>
        createRender(DateField, { Date: item.value.created_at }),
    }),
    table.column({
      accessor: (item: Connection) => {
        const { started_at, closed_at, status } = item;
        if (status === "active") {
          return "-";
        }
        const startedAt = new Date(started_at as string);
        const closedAt = new Date(closed_at as string);
        const diff = closedAt.getTime() - startedAt.getTime();
        return humanizeTimeMs(diff);
      },
      header: "Duration",
    }),
    table.column({
      accessor: (item: Connection) => {
        const { email, first_name, last_name } = item.created_by.user;
        if (first_name) {
          return `${first_name} ${last_name}`;
        }
        return email;
      },
      header: "Created by",
    }),
  ]);
</script>

<div class="space-y-6">
  <h1 class="text-2xl font-bold tracking-tight">Connections</h1>

  <Card.Root class="shadow-sm">
    <Card.Header class="flex flex-col sm:flex-row sm:justify-between gap-4">
      <div>
        <Card.Title class="text-xl">Connection History</Card.Title>
        <Card.Description>View and manage your tunnel connections</Card.Description>
      </div>
      <div class="flex items-center">
        <div class="flex items-center space-x-2">
          <Checkbox id="active-connections" bind:checked class="rounded-sm" />
          <Label
            for="active-connections"
            class="text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70"
          >
            Show active connections
          </Label>
        </div>
      </div>
    </Card.Header>
    <Card.Content>
      <div class="rounded-sm border overflow-hidden">
        <div class="w-full flex justify-end p-2 border-b bg-gray-50">
          <Pagination count={totalItems} perPage={10} currentPage={pageNo} />
        </div>
        <DataTable
          {table}
          {columns}
          isLoading={$connectionsLoading}
          noCard={true}
        />
      </div>
    </Card.Content>
  </Card.Root>
</div>

// tunnel/internal/server/admin/web-v2/src/pages/app/Connections.tsx
import { useState, useEffect } from "react";
import { useParams } from "react-router-dom";
import { Label } from "@/components/ui/label";
import { Checkbox } from "@/components/ui/checkbox";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import ConnectionStatus from "@/components/ConnectionStatus";
import ConnectionType from "@/components/ConnectionType";
import DateField from "@/components/DateField";
import { updateQueryParam } from "@/lib/utils";
import type { Connection } from "@/types";

const humanizeTimeMs = (ms: number): string => {
  const seconds = Math.floor(ms / 1000) % 60;
  const minutes = Math.floor(ms / (1000 * 60)) % 60;
  const hours = Math.floor(ms / (1000 * 60 * 60)) % 24;
  const days = Math.floor(ms / (1000 * 60 * 60 * 24));

  if (days > 0) return `${days}d ${hours}h ${minutes}m ${seconds}s`;
  if (hours > 0) return `${hours}h ${minutes}m ${seconds}s`;
  if (minutes > 0) return `${minutes}m ${seconds}s`;
  return `${seconds}s`;
};

export default function Connections() {
  const { team } = useParams<{ team: string }>();
  const [connections, setConnections] = useState<Connection[]>([]);
  const [connectionsLoading, setConnectionsLoading] = useState(true);
  const [checked, setChecked] = useState(false);

  const urlParams = new URLSearchParams(window.location.search);
  const [connectionType, setConnectionType] = useState(
    urlParams.get("type") || "recent"
  );
  const [pageNo, setPageNo] = useState(
    parseInt(urlParams.get("page") || "1", 10) || 1
  );
  const [totalItems, setTotalItems] = useState(0);

  const getConnections = async (
    type: string = "recent",
    pageNoStr: string = "1"
  ) => {
    if (!team) return;

    setConnectionsLoading(true);
    try {
      const res = await fetch(
        `/api/v1/connections/?type=${type}&page=${pageNoStr}`,
        {
          headers: {
            "x-team-slug": team,
          },
        }
      );

      if (res.ok) {
        const data = await res.json();
        setConnections(data.data || []);
        setTotalItems(data.count || 0);
      }
    } catch (error) {
      console.error("Failed to fetch connections:", error);
      setConnections([]);
      setTotalItems(0);
    } finally {
      setConnectionsLoading(false);
    }
  };

  useEffect(() => {
    if (checked) {
      if (connectionType === "recent") {
        setConnectionType("active");
        setPageNo(1);
      }
    } else {
      if (connectionType === "active") {
        setConnectionType("recent");
        setPageNo(1);
      }
    }
  }, [checked, connectionType]);

  useEffect(() => {
    updateQueryParam(urlParams, "type", connectionType);
    updateQueryParam(urlParams, "page", pageNo.toString());
    getConnections(connectionType, pageNo.toString());
  }, [connectionType, pageNo, team]);

  return (
    <div className="space-y-6">
      <div className="flex justify-between items-center">
        <div>
          <h1 className="text-3xl font-bold tracking-tight">Connections</h1>
          <p className="text-muted-foreground">
            Manage your tunnel connections
          </p>
        </div>

        <div className="flex items-center space-x-2">
          <Checkbox
            id="show-active"
            checked={checked}
            onCheckedChange={(checked) => setChecked(checked as boolean)}
          />
          <Label
            htmlFor="show-active"
            className="text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70"
          >
            Show only active connections
          </Label>
        </div>
      </div>

      <Card>
        <CardHeader className="flex flex-col sm:flex-row sm:justify-between gap-4">
          <div>
            <CardTitle className="text-xl">Connection History</CardTitle>
            <CardDescription>
              View and manage your tunnel connections
            </CardDescription>
          </div>
        </CardHeader>
        <CardContent>
          <div className="rounded-sm border overflow-hidden">
            {connectionsLoading ? (
              <div className="p-6 text-center">
                <p className="text-muted-foreground">Loading connections...</p>
              </div>
            ) : connections.length === 0 ? (
              <div className="p-6 text-center">
                <p className="text-muted-foreground">No connections found</p>
                <p className="text-sm text-muted-foreground mt-1">
                  {connectionType === "active"
                    ? "No active connections at the moment"
                    : "Start a tunnel to see connections here"}
                </p>
              </div>
            ) : (
              <>
                <div className="w-full flex justify-end p-2 border-b bg-muted/50">
                  {/* Pagination would go here */}
                </div>
                <Table>
                  <TableHeader>
                    <TableRow>
                      <TableHead>Type</TableHead>
                      <TableHead>Port</TableHead>
                      <TableHead>Subdomain</TableHead>
                      <TableHead>Status</TableHead>
                      <TableHead>Created at</TableHead>
                      <TableHead>Duration</TableHead>
                      <TableHead>Created by</TableHead>
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    {connections.map((connection) => {
                      const duration =
                        connection.status === "active"
                          ? "-"
                          : connection.started_at && connection.closed_at
                          ? humanizeTimeMs(
                              new Date(connection.closed_at).getTime() -
                                new Date(connection.started_at).getTime()
                            )
                          : "-";

                      return (
                        <TableRow key={connection.id}>
                          <TableCell>
                            <ConnectionType type={connection.type} />
                          </TableCell>
                          <TableCell className="font-mono text-sm">
                            {connection.port || "-"}
                          </TableCell>
                          <TableCell className="font-mono text-sm">
                            {connection.subdomain || "-"}
                          </TableCell>
                          <TableCell>
                            <ConnectionStatus status={connection.status} />
                          </TableCell>
                          <TableCell>
                            <DateField date={connection.created_at} />
                          </TableCell>
                          <TableCell className="text-sm">{duration}</TableCell>
                          <TableCell className="text-sm">
                            {connection.created_by.user.first_name
                              ? `${connection.created_by.user.first_name} ${
                                  connection.created_by.user.last_name || ""
                                }`
                              : connection.created_by.user.email}
                          </TableCell>
                        </TableRow>
                      );
                    })}
                  </TableBody>
                </Table>
              </>
            )}
          </div>
        </CardContent>
      </Card>

      {totalItems > 0 && (
        <div className="flex items-center justify-between">
          <p className="text-sm text-muted-foreground">
            Showing {connections.length} of {totalItems} connections
          </p>
          {/* Simple pagination could be added here */}
        </div>
      )}
    </div>
  );
}
