// internal/server/admin/web/src/lib/components/ConnectionType.svelte
<script lang="ts">
  import { Badge } from "$lib/components/ui/badge";
  import type { ConnectionType } from "$lib/types";

  export let Type: ConnectionType;
</script>

{#if Type === "http"}
  <Badge variant="outline" class="border-blue-300 font-normal">HTTP</Badge>
{:else}
  <Badge variant="outline" class="border-green-300 font-normal">TCP</Badge>
{/if}

// tunnel/internal/server/admin/web-v2/src/components/ConnectionType.tsx
import { Badge } from '@/components/ui/badge'
import type { ConnectionType } from '@/types'

interface ConnectionTypeProps {
  type: ConnectionType
}

export default function ConnectionType({ type }: ConnectionTypeProps) {
  return (
    <Badge variant="outline" className="uppercase font-mono text-xs">
      {type}
    </Badge>
  )
}
