// admin/src/web/src/pages/app/connections.svelte
<script lang="ts">
  import DataTable from "$lib/components/data-table.svelte";
  // @ts-expect-error
  import { createTable, createRender } from "svelte-headless-table";
  import { humanizeTimeMs } from "$lib/humanize";
  import { Checkbox } from "$lib/components/ui/checkbox";
  import Label from "$lib/components/ui/label/label.svelte";
  import { connections, connectionsLoading } from "$lib/store";
  import type { Connection } from "$lib/types";
  import { getContext } from "svelte";
  import ConnectionStatus from "$lib/components/ConnectionStatus.svelte";
  import ConnectionType from "$lib/components/ConnectionType.svelte";
  import DateField from "$lib/components/DateField.svelte";
  import Pagination from "$lib/components/Pagination.svelte";
  import { writable } from "svelte/store";
  import { updateQueryParam } from "$lib/utils";

  let checked = false;
  const urlParams = new URLSearchParams(window.location.search);
  let connectionType = urlParams.get("type") || "recent";

  let pageNo = writable(1);
  let pageNoStr = urlParams.get("page") || "1";
  pageNo.set(parseInt(pageNoStr, 10) || 1);

  $: if (checked) {
    if (connectionType === "recent") {
      connectionType = "active";
      pageNo.set(1);
    }
  } else {
    if (connectionType === "active") {
      connectionType = "recent";
      $pageNo = 1;
    }
  }

  $: updateQueryParam(urlParams, "type", connectionType);
  $: updateQueryParam(urlParams, "page", $pageNo.toString());
  $: getConnections(connectionType, $pageNo.toString());

  let team = getContext("team") as string;

  let totalItems = 0;

  const getConnections = async (
    type: string = "recent",
    pageNo: string = "1"
  ) => {
    connectionsLoading.set(true);
    try {
      const response = await fetch(
        `/api/v1/connections/?type=${type}&page=${pageNo}`,
        {
          headers: {
            "x-team-slug": team,
          },
        }
      );
      const responseData = await response.json();
      connections.set(responseData["data"] || []);
      totalItems = responseData.count;
    } catch (err) {
      console.error(err);
    } finally {
      connectionsLoading.set(false);
    }
  };

  const table = createTable(connections);

  const columns = table.createColumns([
    table.column({
      header: "Type",
      accessor: (item: Connection) => item,
      cell: ({ value: { type } }: { value: { type: string } }) =>
        createRender(ConnectionType, { type }),
    }),
    table.column({
      header: "Port",
      accessor: (item: Connection) => {
        const { port } = item;
        return port ? port : "-";
      },
    }),
    table.column({
      header: "Subdomain",
      accessor: (item: Connection) => {
        const { subdomain } = item;
        return subdomain ? subdomain : "-";
      },
    }),
    table.column({
      accessor: (item: Connection) => item,
      header: "Status",
      cell: ({ value: { status } }: { value: { status: string } }) =>
        createRender(ConnectionStatus, { status }),
    }),
    table.column({
      accessor: (item: Connection) => item,
      header: "Created at",
      cell: (item: any) =>
        createRender(DateField, { Date: item.value.created_at }),
    }),
    table.column({
      accessor: (item: Connection) => {
        const { started_at, closed_at, status } = item;
        if (status === "active") {
          return "-";
        }
        const startedAt = new Date(started_at as string);
        const closedAt = new Date(closed_at as string);
        const diff = closedAt.getTime() - startedAt.getTime();
        return humanizeTimeMs(diff);
      },
      header: "Duration",
    }),
    table.column({
      accessor: (item: Connection) => {
        const { email, first_name, last_name } = item.created_by.user;
        if (first_name) {
          return `${first_name} ${last_name}`;
        }
        return email;
      },
      header: "Created by",
    }),
  ]);
</script>

<div class="p-6">
  <div class="flex items-center py-3 justify-between w-full">
    <div class="flex items-center space-x-2">
      <Checkbox id="terms" bind:checked class="rounded-full" />
      <Label
        for="terms"
        class="text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70"
      >
        Show active connections
      </Label>
    </div>
    <div>
      <Pagination count={totalItems} perPage={10} currentPage={pageNo} />
    </div>
  </div>

  <DataTable {table} {columns} isLoading={$connectionsLoading} />
</div>

// internal/server/admin/web-v2/src/pages/app/Connections.tsx
import { useState, useEffect } from "react";
import { Link, useParams } from "react-router-dom";
import { Label } from "@/components/ui/label";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { Button } from "@/components/ui/button";
import ConnectionType from "@/components/ConnectionType";
import DateField from "@/components/DateField";
import Panel from "@/components/Panel";
import RouteLine, { connectionRouteState } from "@/components/RouteLine";
import SegmentedControl from "@/components/SegmentedControl";
import { Pagination } from "@/components/ui/pagination";
import { Skeleton } from "@/components/ui/skeleton";
import { formatDuration } from "@/lib/humanize";
import { updateQueryParam } from "@/lib/utils";
import type { Connection } from "@/types";

const filters = [
  { value: "recent" as const, label: "All" },
  { value: "active" as const, label: "Active" },
];

type ConnectionFilter = (typeof filters)[number]["value"];

export default function Connections() {
  const { team } = useParams<{ team: string }>();
  const [connections, setConnections] = useState<Connection[]>([]);
  const [connectionsLoading, setConnectionsLoading] = useState(true);

  const urlParams = new URLSearchParams(window.location.search);
  const [connectionType, setConnectionType] = useState<ConnectionFilter>(
    urlParams.get("type") === "active" ? "active" : "recent"
  );
  const [pageNo, setPageNo] = useState(
    parseInt(urlParams.get("page") || "1", 10) || 1
  );
  const [pageSize, setPageSize] = useState(
    parseInt(urlParams.get("page_size") || "10", 10) || 10
  );
  const [totalItems, setTotalItems] = useState(0);

  const getConnections = async (
    type: string = "recent",
    pageNoStr: string = "1",
    pageSizeStr: string = "10"
  ) => {
    if (!team) return;

    setConnectionsLoading(true);
    try {
      const res = await fetch(
        `/api/v1/connections/?type=${type}&page=${pageNoStr}&page_size=${pageSizeStr}`,
        {
          headers: {
            "x-team-slug": team,
          },
        }
      );

      if (res.ok) {
        const data = await res.json();
        setConnections(data.data || []);
        setTotalItems(data.count || 0);
      }
    } catch (error) {
      console.error("Failed to fetch connections:", error);
      setConnections([]);
      setTotalItems(0);
    } finally {
      setConnectionsLoading(false);
    }
  };

  useEffect(() => {
    updateQueryParam(urlParams, "type", connectionType);
    updateQueryParam(urlParams, "page", pageNo.toString());
    updateQueryParam(urlParams, "page_size", pageSize.toString());
    getConnections(connectionType, pageNo.toString(), pageSize.toString());
  }, [connectionType, pageNo, pageSize, team]);

  const columns = ["Type", "Route", "Opened", "Duration", "Opened by"];

  return (
    <div className="space-y-5">
      <div className="flex flex-wrap items-center justify-between gap-3">
        <SegmentedControl<ConnectionFilter>
          ariaLabel="Filter connections"
          options={filters}
          value={connectionType}
          onChange={(value) => {
            setConnectionType(value);
            setPageNo(1);
          }}
        />

        <div className="flex items-center gap-2">
          <Label htmlFor="page-size" className="text-xs text-muted-foreground">
            Rows
          </Label>
          <Select
            value={pageSize.toString()}
            onValueChange={(value) => {
              setPageSize(parseInt(value, 10));
              setPageNo(1);
            }}
          >
            <SelectTrigger className="h-8 w-[4.5rem]" id="page-size" size="sm">
              <SelectValue />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="10">10</SelectItem>
              <SelectItem value="25">25</SelectItem>
              <SelectItem value="50">50</SelectItem>
              <SelectItem value="100">100</SelectItem>
            </SelectContent>
          </Select>
        </div>
      </div>

      <Panel flush>
        {connectionsLoading ? (
          <Table>
            <TableHeader>
              <TableRow>
                {columns.map((column) => (
                  <TableHead key={column}>{column}</TableHead>
                ))}
              </TableRow>
            </TableHeader>
            <TableBody>
              {Array.from({ length: pageSize }).map((_, index) => (
                <TableRow key={index}>
                  {columns.map((column) => (
                    <TableCell key={column}>
                      <Skeleton className="h-4 w-full max-w-40" />
                    </TableCell>
                  ))}
                </TableRow>
              ))}
            </TableBody>
          </Table>
        ) : connections.length === 0 ? (
          <div className="px-6 py-12 text-center">
            <p className="text-sm font-medium">
              {connectionType === "active"
                ? "No tunnels are running"
                : "No connections yet"}
            </p>
            <p className="mx-auto mt-1 max-w-sm text-xs text-muted-foreground">
              {connectionType === "active"
                ? "Connections appear here while a tunnel is open."
                : "Start a tunnel from the Portr client and it shows up here."}
            </p>
            {connectionType !== "active" && (
              <Button asChild variant="outline" size="sm" className="mt-4">
                <Link to={`/${team}/overview`}>Set up the client</Link>
              </Button>
            )}
          </div>
        ) : (
          <Table>
            <TableHeader>
              <TableRow>
                {columns.map((column) => (
                  <TableHead key={column}>{column}</TableHead>
                ))}
              </TableRow>
            </TableHeader>
            <TableBody>
              {connections.map((connection) => {
                const duration =
                  connection.status === "active"
                    ? "—"
                    : connection.started_at && connection.closed_at
                    ? formatDuration(
                        new Date(connection.closed_at).getTime() -
                          new Date(connection.started_at).getTime()
                      )
                    : "—";

                return (
                  <TableRow key={connection.id}>
                    <TableCell>
                      <ConnectionType type={connection.type} />
                    </TableCell>
                    {/* Name, port and state are one binding, not three
                        independent facts — they read as one cell. */}
                    <TableCell className="min-w-64">
                      <RouteLine
                        name={connection.subdomain || `${connection.type} tunnel`}
                        port={connection.port}
                        state={connectionRouteState(connection)}
                      />
                    </TableCell>
                    <TableCell>
                      <DateField date={connection.created_at} />
                    </TableCell>
                    <TableCell className="data text-xs">{duration}</TableCell>
                    <TableCell className="text-sm">
                      {connection.created_by.user.first_name
                        ? `${connection.created_by.user.first_name} ${
                            connection.created_by.user.last_name || ""
                          }`
                        : connection.created_by.user.email}
                    </TableCell>
                  </TableRow>
                );
              })}
            </TableBody>
          </Table>
        )}
      </Panel>

      {totalItems > 0 && (
        <div className="flex flex-wrap items-center justify-between gap-3">
          <p className="text-xs text-muted-foreground">
            <span className="tabular">
              {(pageNo - 1) * pageSize + 1}–
              {Math.min(pageNo * pageSize, totalItems)}
            </span>{" "}
            of <span className="tabular">{totalItems}</span>
          </p>
          <Pagination
            count={totalItems}
            perPage={pageSize}
            currentPage={pageNo}
            onPageChange={setPageNo}
          />
        </div>
      )}
    </div>
  );
}
