// internal/client/dashboard/ui-v2/src/components/ui/checkbox.tsx
import * as React from "react"
import { Checkbox as CheckboxPrimitive } from "radix-ui"

import { cn } from "@/lib/utils"
import { CheckIcon } from "lucide-react"

function Checkbox({
  className,
  ...props
}: React.ComponentProps<typeof CheckboxPrimitive.Root>) {
  return (
    <CheckboxPrimitive.Root
      data-slot="checkbox"
      className={cn(
        "peer relative flex size-4 shrink-0 items-center justify-center rounded-[4px] border border-input transition-colors outline-none group-has-disabled/field:opacity-50 after:absolute after:-inset-x-3 after:-inset-y-2 focus-visible:border-ring focus-visible:ring-3 focus-visible:ring-ring/50 disabled:cursor-not-allowed disabled:opacity-50 aria-invalid:border-destructive aria-invalid:ring-3 aria-invalid:ring-destructive/20 aria-invalid:aria-checked:border-primary dark:bg-input/30 dark:aria-invalid:border-destructive/50 dark:aria-invalid:ring-destructive/40 data-checked:border-primary data-checked:bg-primary data-checked:text-primary-foreground dark:data-checked:bg-primary",
        className
      )}
      {...props}
    >
      <CheckboxPrimitive.Indicator
        data-slot="checkbox-indicator"
        className="grid place-content-center text-current transition-none [&>svg]:size-3.5"
      >
        <CheckIcon />
      </CheckboxPrimitive.Indicator>
    </CheckboxPrimitive.Root>
  )
}

export { Checkbox }

// internal/server/admin/web/src/lib/components/ui/checkbox/checkbox.svelte
<script lang="ts">
  import { Checkbox as CheckboxPrimitive } from "bits-ui";
  import { Check, Minus } from "radix-icons-svelte";
  import { cn } from "$lib/utils";

  type $$Props = CheckboxPrimitive.Props;
  type $$Events = CheckboxPrimitive.Events;

  let className: $$Props["class"] = undefined;
  export let checked: $$Props["checked"] = false;
  export { className as class };
</script>

<CheckboxPrimitive.Root
  class={cn(
    "box-content peer h-4 w-4 shrink-0 rounded-sm border border-primary shadow focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:cursor-not-allowed disabled:opacity-50 data-[state=checked]:bg-primary data-[state=checked]:text-primary-foreground data-[disabled=true]:cursor-not-allowed data-[disabled=true]:opacity-50",
    className
  )}
  bind:checked
  on:click
  {...$$restProps}
>
  <CheckboxPrimitive.Indicator
    class={cn("flex items-center justify-center text-current h-4 w-4")}
    let:isChecked
    let:isIndeterminate
  >
    {#if isIndeterminate}
      <Minus class="h-3.5 w-3.5" />
    {:else}
      <Check class={cn("h-3.5 w-3.5", !isChecked && "text-transparent")} />
    {/if}
  </CheckboxPrimitive.Indicator>
</CheckboxPrimitive.Root>
