// internal/server/admin/web-v2/src/App.tsx
import { BrowserRouter, Routes, Route } from 'react-router-dom'
import { Toaster } from 'sonner'
import HomePage from './pages/home/HomePage'
import AppPage from './pages/app/AppPage'
import NotFound from './pages/NotFound'

function App() {
  return (
    <BrowserRouter>
      <Toaster position="top-right" />
      <Routes>
        <Route path="/" element={<HomePage />} />
        <Route path="/:team/*" element={<AppPage />} />
        <Route path="*" element={<NotFound />} />
      </Routes>
    </BrowserRouter>
  )
}

export default App

// internal/server/admin/web/src/App.svelte
<script lang="ts">
  import "./app.pcss";
  import { Router, Route } from "svelte-routing";
  import { Toaster } from "svelte-sonner";

  import Home from "./pages/home.svelte";
  import Notfound from "./pages/notfound.svelte";
  import App from "./pages/app/app.svelte";
  import Setup from "./pages/setup.svelte";
  export let url = "";
</script>

<Toaster position="top-right" />

<Router {url}>
  <Route path="/"><Home /></Route>
  <Route path="/setup"><Setup /></Route>
  <Route path="/:team/*" let:params><App team={params.team} /></Route>
  <Route path=""><Notfound /></Route>
</Router>
