// internal/server/admin/web-v2/src/components/ConnectionStatus.tsx
import { Badge } from '@/components/ui/badge'
import type { ConnectionStatus } from '@/types'

interface ConnectionStatusProps {
  status: ConnectionStatus
}

export default function ConnectionStatus({ status }: ConnectionStatusProps) {
  const getStatusVariant = (status: ConnectionStatus) => {
    switch (status) {
      case 'active':
        return 'default'
      case 'reserved':
        return 'secondary'
      case 'closed':
        return 'outline'
      default:
        return 'outline'
    }
  }

  const getStatusText = (status: ConnectionStatus) => {
    switch (status) {
      case 'active':
        return 'Active'
      case 'reserved':
        return 'Reserved'
      case 'closed':
        return 'Closed'
      default:
        return status
    }
  }

  return (
    <Badge variant={getStatusVariant(status)} className="capitalize">
      {getStatusText(status)}
    </Badge>
  )
}

// tunnel/internal/server/admin/web/src/lib/components/ConnectionStatus.svelte
<script lang="ts">
  import { Badge } from "$lib/components/ui/badge";
  import type { ConnectionStatus } from "$lib/types";

  export let status: ConnectionStatus;
</script>

{#if status === "closed"}
  <Badge variant="outline" class="border-red-300 font-normal">closed</Badge>
{:else}
  <Badge variant="outline" class="border-fuchsia-300 font-normal">active</Badge>
{/if}
