// internal/server/admin/web/src/App.svelte
<script lang="ts">
  import "./app.pcss";
  // @ts-expect-error
  import { Router, Route } from "svelte-routing";
  import { Toaster } from "svelte-sonner";

  import Home from "./pages/home.svelte";
  import Notfound from "./pages/notfound.svelte";
  import App from "./pages/app/app.svelte";
  export let url = "";
</script>

<Toaster position="top-right" />

<Router {url}>
  <Route path="/"><Home /></Route>
  <Route path="/*"><App /></Route>
  <Route path=""><Notfound /></Route>
</Router>

// internal/client/dashboard/ui-v2/src/App.tsx
import { BrowserRouter, Route, Routes } from "react-router-dom"

import { Toaster } from "@/components/ui/sonner"
import { TooltipProvider } from "@/components/ui/tooltip"
import { HomePage } from "@/pages/home-page"
import { TunnelPage } from "@/pages/tunnel-page"

export function App() {
  return (
    <BrowserRouter>
      <TooltipProvider>
        <Toaster position="top-right" richColors />
        <Routes>
          <Route element={<HomePage />} path="/" />
          <Route element={<TunnelPage />} path="/:id" />
        </Routes>
      </TooltipProvider>
    </BrowserRouter>
  )
}

export default App
