// internal/server/admin/web-v2/src/components/TeamSelector.tsx
import { useState, useEffect } from "react";
import { useParams } from "react-router-dom";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
} from "@/components/ui/select";
import type { Team } from "@/types";

export default function TeamSelector() {
  const { team: currentTeamSlug } = useParams<{ team: string }>();
  const [teams, setTeams] = useState<Team[]>([]);
  const [currentTeam, setCurrentTeam] = useState<Team | null>(null);

  useEffect(() => {
    const getMyTeams = async () => {
      try {
        const response = await fetch("/api/v1/user/me/teams", {
          headers: {
            "Content-Type": "application/json",
          },
        });
        if (response.ok) {
          const teamsData = await response.json();
          setTeams(teamsData);

          // Find current team
          if (currentTeamSlug) {
            const team = teamsData.find(
              (t: Team) => t.slug === currentTeamSlug
            );
            if (team) {
              setCurrentTeam(team);
            }
          }
        }
      } catch (error) {
        console.error("Failed to fetch teams:", error);
      }
    };

    getMyTeams();
  }, [currentTeamSlug]);

  const switchTeams = (value: string) => {
    window.location.href = `/${value}/overview`;
  };

  return (
    <Select value={currentTeamSlug} onValueChange={switchTeams}>
      <SelectTrigger
        aria-label="Switch team"
        className="w-full rounded-md border-sidebar-border bg-background px-2.5 shadow-none hover:bg-sidebar-accent focus-visible:ring-2 data-[size=default]:h-11 group-data-[collapsible=icon]:size-9! group-data-[collapsible=icon]:justify-center group-data-[collapsible=icon]:px-1! group-data-[collapsible=icon]:[&>svg]:hidden"
      >
        <div className="flex min-w-0 items-center gap-2.5">
          <div className="flex size-7 shrink-0 items-center justify-center rounded-sm bg-sidebar-primary text-sidebar-primary-foreground">
            <span className="data text-[0.65rem] font-semibold">
              {currentTeam?.name?.slice(0, 2).toUpperCase() || "TE"}
            </span>
          </div>
          <div className="min-w-0 text-left group-data-[collapsible=icon]:hidden">
            <span className="block truncate text-sm font-medium leading-4">
              {currentTeam?.name || "Select team"}
            </span>
            <span className="data block truncate text-[0.68rem] leading-4 text-muted-foreground">
              {currentTeamSlug || "workspace"}
            </span>
          </div>
        </div>
      </SelectTrigger>
      <SelectContent className="p-0">
        <div className="eyebrow px-2 py-1.5">Your teams</div>
        {teams.map((team) => (
          <SelectItem key={team.id} value={team.slug}>
            <div className="flex items-center gap-2">
              <div className="flex size-6 items-center justify-center rounded-sm bg-muted">
                <span className="data text-[0.62rem] font-semibold">
                  {team.name.slice(0, 2).toUpperCase()}
                </span>
              </div>
              <span>{team.name}</span>
            </div>
          </SelectItem>
        ))}
      </SelectContent>
    </Select>
  );
}

// admin/web/src/lib/components/team-selector.svelte
<script lang="ts">
  import * as Select from "$lib/components/ui/select";
  import { currentUserTeams } from "$lib/store";
  import { getContext, onDestroy, onMount } from "svelte";
  import * as Avatar from "$lib/components/ui/avatar";
  import { createAvatar } from "@dicebear/core";
  import { initials } from "@dicebear/collection";

  let team = getContext("team") as string;

  let selected: any, currentTeam;

  const get_my_teams = async () => {
    const response = await fetch(`/api/v1/user/me/teams`, {
      headers: {
        "Content-Type": "application/json",
      },
    });
    currentUserTeams.set(await response.json());
  };

  const avatar = (text: string) => {
    const svg = createAvatar(initials, {
      seed: text,
    });
    // @ts-ignore
    return `data:image/svg+xml,${encodeURIComponent(svg)}`;
  };

  const subscriber = currentUserTeams.subscribe((teams) => {
    currentTeam = teams.filter((item) => item.slug === team)[0];
    selected = { label: currentTeam?.name, value: currentTeam?.slug };
  });

  const switchTeams = (item: any) => {
    location.href = `/${item.value}/overview`;
  };

  onMount(() => {
    get_my_teams();
  });

  onDestroy(() => subscriber());
</script>

<Select.Root bind:selected onSelectedChange={switchTeams}>
  <Select.Trigger class="text-[14px] focus:ring-0">
    <div class="flex items-center space-x-2">
      <Avatar.Root class="w-5 h-5 rounded-full">
        <Avatar.Image
          src={avatar(selected.label)}
          alt={selected.label}
          class="w-5 h-5 rounded-full border mr-2"
        />
      </Avatar.Root>
      <Select.Value />
    </div>
  </Select.Trigger>
  <Select.Content>
    <Select.Group>
      <Select.Label>Your teams</Select.Label>
      {#each $currentUserTeams as team}
        <Select.Item value={team.slug} label={team.name}>
          <img
            src={avatar(team.name)}
            alt={team.name}
            class="w-5 h-5 rounded-full border mr-2"
          />
          {team.name}
        </Select.Item>
      {/each}
    </Select.Group>
  </Select.Content>
  <Select.Input name="favoriteFruit" />
</Select.Root>
