// tunnel/internal/server/admin/web/src/pages/app-layout.svelte
<script lang="ts">
  import IssueLink from "$lib/components/issue-link.svelte";
  import { Button } from "$lib/components/ui/button";
</script>

<div class="h-screen w-full flex">
  <div class="hidden md:flex md:w-[220px] lg:w-[260px] border-r border-gray-300 bg-white">
    <slot name="sidebar" />
  </div>
  <div class="flex flex-col flex-1 min-w-0">
    <header
      class="flex h-14 items-center gap-4 border-b border-gray-300 bg-white px-4 lg:h-[60px] lg:px-6 flex-shrink-0"
    >
      <div class="w-full flex-1 flex items-center justify-end">
        <IssueLink />
      </div>
    </header>
    <main class="flex-1 overflow-y-auto bg-white">
      <div class="flex flex-col gap-4 p-4 lg:gap-6 lg:p-6">
        <slot name="body" />
      </div>
    </main>
  </div>
</div>

// internal/server/admin/web-v2/src/components/AppLayout.tsx
import type { ReactNode } from "react";
import {
  SidebarProvider,
  Sidebar,
  SidebarInset,
  SidebarTrigger,
} from "@/components/ui/sidebar";
import IssueLink from "./IssueLink";

interface AppLayoutProps {
  sidebar: ReactNode;
  children: ReactNode;
}

export default function AppLayout({ sidebar, children }: AppLayoutProps) {
  return (
    <SidebarProvider>
      <Sidebar>{sidebar}</Sidebar>
      <SidebarInset>
        <header className="flex h-14 items-center gap-4 border-b px-4 lg:h-[60px] lg:px-6">
          <SidebarTrigger className="-ml-1" />
          <div className="flex-1" />
          <IssueLink />
        </header>
        <main className="flex-1 overflow-y-auto">
          <div className="flex flex-col gap-4 p-4 lg:gap-6 lg:p-6">
            {children}
          </div>
        </main>
      </SidebarInset>
    </SidebarProvider>
  );
}
