// tunnel/internal/server/admin/web/src/lib/components/sidebarlink.svelte
<script lang="ts">
  import { Link } from "svelte-routing";

  export let url: string;
  export let extraClass: string = "";
</script>

<div>
  <Link let:active to={url}>
    <div
      class="flex items-center gap-3 rounded-lg px-3 py-2 transition-all hover:text-primary text-sm font-medium {active
        ? 'bg-[#f2f0f0] text-black'
        : 'text-muted-foreground'} {extraClass}"
    >
      <slot />
    </div>
  </Link>
</div>

// internal/server/admin/web-v2/src/components/SidebarLink.tsx
import type { ReactNode } from "react";
import { Link, useLocation } from "react-router-dom";
import { cn } from "@/lib/utils";

interface SidebarLinkProps {
  to: string;
  children: ReactNode;
  className?: string;
}

export default function SidebarLink({
  to,
  children,
  className,
}: SidebarLinkProps) {
  const location = useLocation();
  const isActive = location.pathname === to;

  return (
    <Link
      to={to}
      aria-current={isActive ? "page" : undefined}
      className={cn(
        "flex h-10 items-center gap-3 rounded-xl px-3 text-[0.875rem] font-medium text-sidebar-foreground/75 transition-[background-color,color,transform] hover:bg-sidebar-accent hover:text-sidebar-accent-foreground focus-visible:ring-2 focus-visible:ring-sidebar-ring",
        isActive &&
          "bg-sidebar-primary text-sidebar-primary-foreground shadow-[0_1px_2px_rgba(23,33,30,0.18)] hover:bg-sidebar-primary hover:text-sidebar-primary-foreground",
        className
      )}
    >
      {children}
    </Link>
  );
}
